# This is a basic workflow to help you get started with Actions

name: Deploy Aylex Portfolio

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["general"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Grant the action the permissions
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run one command
        run: echo Testing one command

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
            npm install
            npm run-script build
        env:
            REACT_APP_GITHUBGRAPHQL_TOKEN: ${{ secrets.GITHUBGRAPHQL_TOKEN }}
            
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
            BRANCH: gh-pages
            FOLDER: build
