# This is a basic workflow to help you get started with Actions

name: Deploy Aylex Portfolio

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["general"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Grant the action the permissions
permissions:
  contents: write
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Get Test Secret
        run: echo ${{ REACT_APP_TESTSECRET }}

      # Runs a set of commands using the runners shell
      - name: Build
        env:
            REACT_APP_GITHUBGRAPHQL_TOKEN: ${{ secrets.REACT_APP_GITHUBGRAPHQL_TOKEN }}
        run: |
            npm install
            npm run build
            
     # - name: Deploy
     #   uses: JamesIves/github-pages-deploy-action@releases/v4
     #   with:
     #       BRANCH: gh-pages
     #       FOLDER: build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./build
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
